language: node_js
cache:
  directories:
    - ~/.npm
install:
  - yarn
  - yarn flow:typed
notifications:
  email: false
script:
  - yarn validate
node_js:
  - '9'
  - '8'
after_success:
  - yarn test:report:coverage
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
