export default {
  WIZARD_NEXT_STEP: 'WIZARD_NEXT_STEP',
  WIZARD_PREVIOUS_STEP: 'WIZARD_PREVIOUS_STEP',
  WIZARD_GO_TO_STEP: 'WIZARD_GO_TO_STEP',
  WIZARD_FORM_SUBMIT: 'WIZARD_FORM_SUBMIT',
  WIZARD_ERRORS: 'WIZARD_ERRORS',
  WIZARD_COMPLETE: 'WIZARD_COMPLETE'
};
