export default {
  WIZARD_NEXT_STEP: 'WIZARD_NEXT_STEP',
  WIZARD_PREVIOUS_STEP: 'WIZARD_PREVIOUS_STEP',
  WIZARD_GO_TO_STEP: 'WIZARD_GO_TO_STEP',
  WIZARD_FORM_SUBMIT: 'WIZARD_FORM_SUBMIT',
  WIZARD_LOAD: 'WIZARD_LOAD'
};
